openapi: 3.0.0
info:
  title: Bluehost Deployment Proxy
  description: the deployment proxy api
  contact:
    email: admin@bluehost.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: /api/v1
    description: Bluehost Deployment Proxy
paths:
  /:
    get:
      summary: get healthcheck
      operationId: dproxy.controllers.healthcheck.get_healthcheck
      responses:
        "200":
          description: health is good
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthCheck'
  /rollout:
    post:
      summary: create a rollout
      operationId: dproxy.controllers.rollout.post_rollout
      requestBody:
        description: Create Rollout object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollOut'
        required: true
      responses:
        default:
          description: successful operation
  /rollback:
    post:
      summary: create a rollback
      operationId: dproxy.controllers.rollback.post_rollback
      requestBody:
        description: Create Rollback object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollBack'
        required: true
      responses:
        default:
          description: successful operation
  /register:
    post:
      summary: register a new server
      operationId: dproxy.controllers.register.post_register_server
      requestBody:
        description: Create Server object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterServer'
        required: true
      responses:
        default:
          description: successful operation
  /server:
    patch:
      summary: update server object
      operationId: dproxy.controllers.server.patch_server
      requestBody:
        description: Patch Server Object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Server'
        required: true
      responses:
        default:
          description: successful operation
  /server/history:
    post:
      summary: post server history
      operationId: dproxy.controllers.server.post_server_history
      requestBody:
        description: Post Server History
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerHistory'
        required: True
      responses:
        default:
          description: successful operation
  /versionlock/{hostname}:
    get:
      tags:
      - admins
      summary: Get server versionlock
      operationId: dproxy.controllers.versionlock.get_versionlock
      parameters:
      - name: hostname
        in: path
        description: a base64 encoded server endpoint hostname.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionLock'
        "400":
          description: Invalid hostname supplied
        "404":
          description: Server versionlock not found
components:
  schemas:
    HealthCheck:
      type: object
      properties:
        id:
          type: integer
          example: 1
        status:
          type: string
          example: good
        created_at:
          type: string
          example: 2020-07-26T17:16:29.051842
    RollOut:
      type: object
      properties:
        server_id:
          type: integer
          example: 1
        deployment_id:
          type: integer
          example: 1
        action:
          type: string
          example: UPDATE
        output:
          type: string
          example: deployment was successful
        yum_transaction_id:
          type: integer
          example: 1
        yum_rollback_id:
          type: integer
          example: 1
        hosts:
          type: array
    RollBack:
      type: object
      properties:
        server_id:
          type: integer
          example: 1
        deployment_id:
          type: integer
          example: 1
        action:
          type: string
          example: UPDATE
        output:
          type: string
          example: deployment was successful
        yum_transaction_id:
          type: integer
          example: 1
        yum_rollback_id:
          type: integer
          example: 1
        hosts:
          type: array
    RegisterServer:
      type: object
      properties:
        hostname:
          type: string
          example: my1.test.unifiedlayer.com
        ip:
          type: string
          example: 3.94.46.110
        port:
          type: string
          example: 8003
        protocol:
          type: string
          example: https
        version:
          type: string
          example: v1
        created_by:
          type: string
          example: dclient
        state:
          type: string
          enum: [NEW, ACTIVE, ERROR, UPDATING, DISABLED]
        group:
          type: string
          example: hp_my
        environment:
          type: string
          example: production
        location:
          type: string
          example: provo1
        deployment_proxy:
          type: string
          example: deploy-proxy.hp.provo1.endurancemb.com
    Server:
      type: object
      properties:
        hostname:
          type: string
          example: my1.test.unifiedlayer.com
        ip:
          type: string
          example: 3.94.46.110
        port:
          type: string
          example: 8003
        protocol:
          type: string
          example: https
        version:
          type: string
          example: v1
        group_id:
          type: integer
          example: 1
        environment_id:
          type: integer
          example: 1
        created_by:
          type: string
          example: jmbushman
        state:
          type: string
          enum: [NEW, ACTIVE, ERROR, UPDATING, DISABLED]
    ServerHistory:
      type: object
      properties:
        server_id:
          type: integer
          example: 1
        deployment_id:
          type: integer
          example: 1
        action:
          type: string
          example: UPDATE
        output:
          type: string
          example: deployment was successful
        yum_transaction_id:
          type: integer
          example: 1
        yum_rollback_id:
          type: integer
          example: 1
    Update:
      type: object
      properties:
        hostname:
          type: string
          example: deploy-proxy.hp.provo1.endurancemb.com
        port:
          type: string
          example: 8002
        hosts:
          type: array
    VersionLock:
      type: object
      properties:
        versionlock:
          type: array
          example: ["eig-hp-hp_my-20200527-1.b44ee87.el7.noarch.rpm", "eig-hp-hp_my-20200610-1.b44ee87.el7.noarch.rpm"]
        hostname:
          type: string
          example: my1.test.unifiedlayer.com
        port:
          type: string
          example: 8003

